version: '3.7'

services:
  instruments-db:
    image: mongo
    env_file:
      - ./Backend/InstrumentsService/.env.production
    ports:
      - '27017:27017'
    networks:
      global_network:
        ipv4_address: 192.168.101.20

    volumes:
      - instruments-volume:/data/db

  tags-instruments-db:
    image: mongo
    env_file:
      - ./Backend/TagsInstrumentsService/.env.production
    ports:
      - '27018:27017'
    networks:
      global_network:
        ipv4_address: 192.168.101.21
    volumes:
      - tags-instruments-volume:/data/db
    
  unit-process-db:
    image: mongo
    env_file:
      - ./Backend/unit-process-service/.env.production
    ports:
      - '27019:27017'
    networks:
      global_network:
        ipv4_address: 192.168.101.22
    volumes:
      - unit-process-volume:/data/db

  instruments-service:
    build: ./Backend/InstrumentsService/
    env_file:
      - ./Backend/InstrumentsService/.env.production
    ports:
      - '8081:8080'
    depends_on:
      - instruments-db
      - eureka-service
    networks:
      global_network:
        ipv4_address: 192.168.101.2

  tags-instruments-service:
    build: ./Backend/TagsInstrumentsService/
    env_file:
      - ./Backend/TagsInstrumentsService/.env.production
    ports:
      - '8082:8080'
    depends_on:
      - tags-instruments-db
      - eureka-service
    networks:
      global_network:
        ipv4_address: 192.168.101.3

  unit-process-service:
    build: ./Backend/unit-process-service/.
    env_file:
      - ./Backend/unit-process-service/.env.production
    ports:
      - '3000:3000'
    depends_on:
      - unit-process-db
      - eureka-service
    networks:
      global_network:
        ipv4_address: 192.168.101.4

  eureka-service:
    build: ./Backend/EurekaService/.
    ports:
      - '8761:8761'
    networks:
      global_network:
        ipv4_address: 192.168.101.10

  gateway-service:
    build: ./Backend/GatewayService/.
    env_file:
      - ./Backend/GatewayService/.env.production
    ports:
      - '8080:8080'
    depends_on:
      - eureka-service
      - instruments-service
      - tags-instruments-service
      - unit-process-service
    networks:
      global_network:
        ipv4_address: 192.168.101.50

networks:
  global_network:
    driver: macvlan
    driver_opts:
      parent: 'wlp0s20f3'
      macvlan_mode: 'bridge'
    ipam:
      config:
        - subnet: '192.168.101.0/24'
          gateway: '192.168.101.1'

volumes:
  instruments-volume:
  tags-instruments-volume:
  unit-process-volume:
