services:
  instruments-db:
    image: mongo
    env_file:
      - ./Backend/InstrumentsService/.env.production
    ports:
      - '27017:27017'
    networks:
      global_network:
        ipv4_address: 172.29.48.20

    volumes:
      - instruments-volume:/data/db

  tags-instruments-db:
    image: mongo
    env_file:
      - ./Backend/TagsInstrumentsService/.env.production
    ports:
      - '27018:27017'
    networks:
      global_network:
        ipv4_address: 172.29.48.21
    volumes:
      - tags-instruments-volume:/data/db
    
  unit-process-db:
    image: mongo
    env_file:
      - ./Backend/unit-process-service/.env.production
    ports:
      - '27019:27017'
    networks:
      global_network:
        ipv4_address: 172.29.48.22
    volumes:
      - unit-process-volume:/data/db
      
  # instruments-service:
  #   build: ./Backend/InstrumentsService/
  #   env_file:
  #     - ./Backend/InstrumentsService/.env.production
  #   ports:
  #     - '8081:8080'
  #   depends_on:
  #     - instruments-db
  #     - eureka-service
  #   networks:
  #     global_network:
  #       ipv4_address: 172.29.48.2

  # tags-instruments-service:
  #   build: ./Backend/TagsInstrumentsService/
  #   env_file:
  #     - ./Backend/TagsInstrumentsService/.env.production
  #   ports:
  #     - '8082:8080'
  #   depends_on:
  #     - tags-instruments-db
  #     - eureka-service
  #   networks:
  #     global_network:
  #       ipv4_address: 172.29.48.3

  # unit-process-service:
  #   build: ./Backend/unit-process-service/.
  #   env_file:
  #     - ./Backend/unit-process-service/.env.production
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - unit-process-db
  #     - eureka-service
  #   networks:
  #     global_network:
  #       ipv4_address: 172.29.48.4

  # eureka-service:
  #   build: ./Backend/EurekaService/.
  #   ports:
  #     - '8761:8761'
  #   networks:
  #     global_network:
  #       ipv4_address: 172.29.48.10

  # gateway-service:
  #   build: ./Backend/GatewayService/.
  #   env_file:
  #     - ./Backend/GatewayService/.env.production
  #   ports:
  #     - '8080:8080'
  #   depends_on:
  #     - eureka-service
  #     - instruments-service
  #     - tags-instruments-service
  #     - unit-process-service
  #   networks:
  #     global_network:
  #       ipv4_address: 172.29.48.50

networks:
  global_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.29.48.0/24

volumes:
  instruments-volume:
  tags-instruments-volume:
  unit-process-volume:
