FROM rust:1.85 AS build

COPY ./src ./src
COPY  ./migration ./migration
COPY ./Cargo.toml ./Cargo.toml
COPY ./Cargo.lock ./Cargo.lock

WORKDIR /src
RUN cargo build --release

FROM rust:1.85

COPY --from=build /target/release/user-service .
CMD ["./user-service"]
